apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: i-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: i-app.zzz  # Change this to your domain or localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: i-service
                port:
                  number: 80
